PS1='\[\e[0;31m\]\u\[\e[m\]\[\e[0;33m\]@\h\[\e[m\]:\[\e[1;36m\]\w\[\e[m\]\[\e[1;31m\] \$\[\e[m\] '
alias tree='tree -C'
alias ls='ls -G'
alias lf='ls -F'
alias la='ls -larth'
alias grep='grep --color=auto'
alias vi='vim'
alias amplxe-cl='/opt/intel/vtune_amplifier_xe_2013/bin64/amplxe-cl'
