set hlsearch
set number
set ruler
set title
set ai
set laststatus=2

set nocompatible
set ic
set lbr

filetype indent on

set nocompatible                " be iMproved, required
filetype on                     " required
filetype off                    " required

" Vundle
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" let Vundle manage Vundle, required

" Vundle Plugins
Plugin 'gmarik/Vundle.vim'
" For React
Plugin 'maxmellon/vim-jsx-pretty'
" Fix whitespace
Plugin 'bronson/vim-trailing-whitespace'
" All of your Plugins must be added before the following line
call vundle#end()               " required
filetype plugin indent on       " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just
" :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" alias for FixWhitespace
:command F FixWhitespace

set shiftwidth=4
set tabstop=4
set softtabstop=4
set smarttab expandtab
set autoindent smartindent
autocmd Filetype javascript,xml,html,vue setlocal ts=2 sts=2 sw=2

" UI
set number ruler showmode
"set cursorline          " highlight current line
set scrolloff=1         " keep at least 1 lines above/below
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw only when we need to.
set showmatch           " highlight matching [{()}]

" searching
"set incsearch           " search as characters are entered
set hlsearch            " highlight matches
set ignorecase smartcase " case-sensitive search only for UpperCASE
set magic               " Allows pattern matching with special characters.

" folding
set foldenable
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=marker

" backup
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set backupskip=/tmp/*,/private/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp
set writebackup

" Syntax highlight style
syntax enable
"syntax off

" Switch for syntax highlight
nnoremap E :if exists("g:syntax_on") <Bar>
  \   syntax off <Bar>
  \ else <Bar>
  \   syntax enable <Bar>
  \ endif <CR>
